steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/cbd3354-systems/flask-app:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/cbd3354-systems/flask-app:$COMMIT_SHA'

  # Step 3: Deploy the new image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'set'
      - 'image'
      - 'deployment/flask-app'
      - 'flask-app=gcr.io/cbd3354-systems/flask-app:$COMMIT_SHA'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=geminiai-cluster'

images:
  - 'gcr.io/cbd3354-systems/flask-app:$COMMIT_SHA'